# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fdbb3b5cb767a6085004fe1ce90d56bf256d32a1fca1c1304d78cb9f17381b8302fb7f65e333132f5a38318e27c89d21383492d28339dd14ecd0343c9c6f2e0

test:
  secret_key_base: 84b8674de3ac3f14ac093723b65f654443bf6c6d54cd240b258650345a6c3bb140603cac75d7893f7d44ec89dee2b5d543060076d6d7065c95530af5cfb14fa1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
